#pragma once

#include "Graphics/API/DX12/DX12Includes.h"

#if defined(GFX_API_DX12)

static D3D12_COMMAND_QUEUE_FLAGS DX12CommandQueueFlags[2] = 
{ 
	D3D12_COMMAND_QUEUE_FLAG_NONE, 
	D3D12_COMMAND_QUEUE_FLAG_DISABLE_GPU_TIMEOUT 
};

static D3D12_COMMAND_LIST_TYPE DX12CommandListTypes[6] = 
{ 
	D3D12_COMMAND_LIST_TYPE_DIRECT,
	D3D12_COMMAND_LIST_TYPE_BUNDLE,
	D3D12_COMMAND_LIST_TYPE_COMPUTE,
	D3D12_COMMAND_LIST_TYPE_COPY,
	D3D12_COMMAND_LIST_TYPE_VIDEO_DECODE,
	D3D12_COMMAND_LIST_TYPE_VIDEO_PROCESS
};

#endif